---
# The update channel to subscribe to (e.g., gitops-1.10, gitops-1.11, latest)
gitops_version: 1.18
gitops_operator_channel: "gitops-{{ gitops_version }}"

# The name of the CatalogSource
gitops_operator_source: "redhat-operators"

# The namespace of the CatalogSource
gitops_operator_source_namespace: "openshift-marketplace"

# The namespace to install the operator into
gitops_operator_namespace: "openshift-gitops-operator"

# Target Cluster Set for Policies
spokes_clusterset: default