---
- name: Deploy Global-to-Regional Alerting Policy
  kubernetes.core.k8s:
    kubeconfig: "{{ target_kubeconfig }}"
    state: present
    template: regional-alerts-policy.yaml.j2

- name: Deploy Placement and Binding for Regional Hubs
  kubernetes.core.k8s:
    kubeconfig: "{{ target_kubeconfig }}"
    state: present
    template: regional-alerts-placement.yaml.j2