---
- name: Install Day 2 Config via OpenShift GitOps (ArgoCD)
  hosts: localhost
  vars_files:
    - ../group_vars/all.yaml
  connection: local
  gather_facts: false

  tasks:
    - name: Install ArgoCD App - ACM
      ansible.builtin.include_role:
        name: argo/apps_install_acm
      vars:
        target_kubeconfig: "{{ install_dir }}/{{ cluster_name }}/auth/kubeconfig"

    - name: Install ArgoCD App - ODF
      ansible.builtin.include_role:
        name: argo/apps_install_odf
      vars:
        target_kubeconfig: "{{ install_dir }}/{{ cluster_name }}/auth/kubeconfig"

    - name: Install ArgoCD App - MCO
      ansible.builtin.include_role:
        name: argo/apps_install_mco
      vars:
        target_kubeconfig: "{{ install_dir }}/{{ cluster_name }}/auth/kubeconfig"

#    - name: Install ArgoCD App - Global Hub
#      ansible.builtin.include_role:
#        name: argo/apps_install_global_hub
#      vars:
#        target_kubeconfig: "{{ install_dir }}/{{ cluster_name }}/auth/kubeconfig"
