---
- name: Deploy ACM Policies to Regional Hub
  hosts: localhost
  vars_files:
    - ../group_vars/all.yaml
  connection: local
  gather_facts: false

  tasks:
    - name: Deploy ACM Policy - OpenShift GitOps 1.18
      ansible.builtin.include_role:
        name: acm/policy_install_openshift_gitops_1.18
      vars:
        target_kubeconfig: "{{ install_dir }}/{{ cluster_name }}/auth/kubeconfig"
        spokes_clusterset: "{{ spokes_clusterset | default('default') }}"

    - name: Deploy ACM Policy - OpenShift GitOps 1.19
      ansible.builtin.include_role:
        name: acm/policy_install_openshift_gitops_1.19
      vars:
        target_kubeconfig: "{{ install_dir }}/{{ cluster_name }}/auth/kubeconfig"
        spokes_clusterset: "{{ spokes_clusterset | default('default') }}"
