---
- name: Deploy Monitoring Policy to Global Hub
  hosts: localhost
  vars_files:
    - ../group_vars/all.yaml
  connection: local
  gather_facts: false

  tasks:
    - name: Deploy ACM Policy - Monitor Managed Hubs
      ansible.builtin.include_role:
        name: acm/policy_monitor_managed_hubs
      vars:
        target_kubeconfig: "{{ install_dir }}/{{ cluster_name }}/auth/kubeconfig"
