---
- name: Deploy Enterprise Observability Alerts to Global Hub
  hosts: localhost
  vars_files:
    - ../group_vars/all.yaml
  connection: local
  gather_facts: false

  tasks:
    - name: Deploy Alerting Policies to the Global Hub
      ansible.builtin.include_role:
        name: acm/policy_install_observability_alerts
      vars:
        target_kubeconfig: "{{ install_dir }}/{{ cluster_name }}/auth/kubeconfig"
        spokes_clusterset: "{{ spokes_clusterset | default('default') }}"
