---
- name: Install ArgoCD via ACM Policy
  hosts: localhost
  vars_files:
    - ../group_vars/all.yaml
  connection: local
  gather_facts: false
  environment:
    KUBECONFIG: "{{ install_dir }}/{{ ocp_cluster.name }}/auth/kubeconfig"

  roles:
    - role: acm/policy_install_openshift_gitops_1.18
    - role: acm/policy_install_openshift_gitops_1.19